// checksum 0xc67a version 0x80016
/*
  This file was generated by the Qt Quick Application wizard of Qt Creator.
  QmlApplicationViewer is a convenience class containing mobile device specific
  code such as screen orientation handling. Also QML paths and debugging are
  handled here.
  It is recommended not to modify this file, since newer versions of Qt Creator
  may offer an updated version of it.
*/

#ifndef QMLAPPLICATIONVIEWER_H
#define QMLAPPLICATIONVIEWER_H
#include <qglobal.h>

#if QT_VERSION < QT_VERSION_CHECK (5, 0, 0)
#include <QDeclarativeView>
class QmlApplicationViewer : public QDeclarativeView
#else
#include <QCoreApplication>
#include <QGuiApplication>
#include <QQuickView>
class QmlApplicationViewer : public QQuickView
#endif
{
    Q_OBJECT

public:
    enum ScreenOrientation {
        ScreenOrientationLockPortrait,
        ScreenOrientationLockLandscape,
        ScreenOrientationAuto
    };
#if QT_VERSION < QT_VERSION_CHECK (5, 0, 0)
    explicit QmlApplicationViewer(QWidget *parent = 0);
#else
    explicit QmlApplicationViewer(QWindow *parent = 0);
#endif
    virtual ~QmlApplicationViewer();

    static QmlApplicationViewer *create();

    void setMainQmlFile(const QString &file);
    void addImportPath(const QString &path);

    // Note that this will only have an effect on Fremantle.
    void setOrientation(ScreenOrientation orientation);

    void showExpanded();


private:
    explicit QmlApplicationViewer(QQuickView *view, QWindow *parent);
    class QmlApplicationViewerPrivate *d;
};

#if QT_VERSION < QT_VERSION_CHECK (5, 0, 0)
QApplication *createApplication(int &argc, char **argv);
#else
QGuiApplication *createApplication(int &argc, char **argv);
#endif

#endif // QMLAPPLICATIONVIEWER_H
